// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using u22543024_HW01_API.Data;

#nullable disable

namespace u22543024_HW01_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("u22543024_HW01_API.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "High-performance running shoes designed with breathable mesh and a cushioned sole for maximum comfort and support. Features a sleek design and durable rubber outsole for traction on various surfaces.",
                            Name = "Running Shoes",
                            Price = 89.989999999999995
                        },
                        new
                        {
                            ID = 2,
                            Description = "Sleek leather boots with elastic side panels for easy wear. Features a comfortable insole and durable rubber outsole, ideal for everyday wear.",
                            Name = "Boots",
                            Price = 89.0
                        },
                        new
                        {
                            ID = 3,
                            Description = "A classic baseball cap with an adjustable strap and embroidered logo. Made of breatable cotton, perfect for casual and outdoor activities.",
                            Name = "Baseball Cap",
                            Price = 19.989999999999998
                        },
                        new
                        {
                            ID = 4,
                            Description = "Flowing, floor-length mix dress made from lightweight fabric. Features an adjustable strap design and a flattering A-line sihouette.",
                            Name = "Maxi Dress",
                            Price = 59.990000000000002
                        },
                        new
                        {
                            ID = 5,
                            Description = "A pair of slim-fit chinos made from lightweight cotton with a bit of stretch. Features a clean, modern look suitable for both work and weekend wear.",
                            Name = "Slim Fit Chinos",
                            Price = 44.950000000000003
                        },
                        new
                        {
                            ID = 6,
                            Description = "Cozy hoodie with a bold graphic print on the front. Made of soft cotton, perfect for lounging or casual outings.",
                            Name = "Hoodie",
                            Price = 49.990000000000002
                        },
                        new
                        {
                            ID = 7,
                            Description = "Comfortable and stylish jogger sweatpants with an elastic waistband and cuffs. Features side pockets and a soft fleece interior for extra warmth.",
                            Name = "Jogger Sweatpants",
                            Price = 39.990000000000002
                        },
                        new
                        {
                            ID = 8,
                            Description = "A fleece jacket is a lightweight, warm, and breathable outwear piece made from synthetic material like polyster. It provides excellent insulation by trapping heat while remaing soft and comfortable. Fleece jackets are popular for outdoor activities, layering in cold casual wear due to thier moisture-wicking properties and ease of care.",
                            Name = "Fleece Jacket",
                            Price = 70.0
                        },
                        new
                        {
                            ID = 9,
                            Description = "Jeans are durable pants made from from demin fabric, designed as workwear but suitable for casual and fashion wear. Feature a button or ziper fly, belt loops, and pockets. They come in various shades, from classic blue to black, white, and distressed finishes. ",
                            Name = "Jeans",
                            Price = 600.0
                        },
                        new
                        {
                            ID = 10,
                            Description = "A T-Shirt is a casual, short-sleeved garment made from soft fabric, typically cotton. Designed with a round or V-shaped neckline, in various colours, patterns, and styles, including fitted, oversized, and grphic-printed designs.",
                            Name = "T-Shirt",
                            Price = 67.989999999999995
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
